spring.application.name=ISC-AUTH
spring.config.import=optional:file:.env[.properties]
spring.devtools.add-properties=true

server.port=${SERVER_PORT}

spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secretKey=${JWT_SECRET}
jwt.timeExpiration=${JWT_EXPIRATION}
jwt.resetPasswordExpiration=${JWT_RESET_EXPIRATION}

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/api/v1/docs/index.html

email.username=${EMAIL_USERNAME}
email.password=${EMAIL_PASSWORD}

frontend.url=${FRONTEND_URL}
test.url=${TEST_URL}

server.forward-headers-strategy=framework
